import { AuditLogEvent, EmbedBuilder, PermissionFlagsBits, type Guild, type GuildAuditLogsEntry } from 'discord.js';
import { loadGuild, updateGuild } from '../storage.js';
import { isAntiNukeTrusted } from '../security.js';
import type { AntiNukeLimit } from '../types.js';

const counters = new Map<string, number[]>();
const ACTIONS: Record<number, keyof ReturnType<typeof loadGuild>['antiNuke']['limits'] | 'bot_add'> = {
  [AuditLogEvent.ChannelDelete]:'channel_delete', [AuditLogEvent.ChannelCreate]:'channel_create', [AuditLogEvent.RoleDelete]:'role_delete', [AuditLogEvent.RoleCreate]:'role_create',
  [AuditLogEvent.MemberBanAdd]:'member_ban', [AuditLogEvent.MemberKick]:'member_kick', [AuditLogEvent.WebhookCreate]:'webhook_create', [AuditLogEvent.WebhookDelete]:'webhook_delete',
  [AuditLogEvent.ChannelUpdate]:'permission_update', [AuditLogEvent.RoleUpdate]:'permission_update', [AuditLogEvent.BotAdd]:'bot_add',
};
function hit(key:string,limit:AntiNukeLimit):number{const now=Date.now();const arr=(counters.get(key)??[]).filter(t=>now-t<limit.windowSeconds*1000);arr.push(now);counters.set(key,arr);return arr.length;}
async function log(guild:Guild,title:string,description:string,color:number,fields:{name:string,value:string,inline?:boolean}[]=[]):Promise<void>{let id=loadGuild(guild.id).antiNuke.logChannelId;let channel=id?await guild.channels.fetch(id).catch(()=>null):null;if(!channel){const me=guild.members.me??await guild.members.fetchMe().catch(()=>null);if(me?.permissions.has(PermissionFlagsBits.ManageChannels)){channel=await guild.channels.create({name:'antinuke-logs',reason:'Anti-Nuke security logging'}).catch(()=>null);if(channel)updateGuild(guild.id,d=>{d.antiNuke.logChannelId=channel!.id;});}}const em=new EmbedBuilder().setColor(color).setTitle(title).setDescription(description).addFields(fields).setFooter({text:'Sparxie • Anti-Nuke Security'}).setTimestamp();if(channel?.isTextBased())await channel.send({embeds:[em]}).catch(()=>undefined);else console.warn(`[AntiNuke] ${title}: ${description}`);}
async function stripDangerousRoles(guild:Guild,executorId:string):Promise<string[]>{const member=await guild.members.fetch(executorId).catch(()=>null);if(!member)return[];const me=guild.members.me??await guild.members.fetchMe().catch(()=>null);if(!me)return[];const removed:string[]=[];for(const role of [...member.roles.cache.values()]){if(role.id===guild.id||!role.editable||role.position>=me.roles.highest.position)continue;if(role.permissions.has(PermissionFlagsBits.Administrator)||role.permissions.has(PermissionFlagsBits.ManageGuild)||role.permissions.has(PermissionFlagsBits.ManageChannels)||role.permissions.has(PermissionFlagsBits.ManageRoles)||role.permissions.has(PermissionFlagsBits.BanMembers)||role.permissions.has(PermissionFlagsBits.KickMembers)||role.permissions.has(PermissionFlagsBits.ManageWebhooks)){await member.roles.remove(role,'Anti-Nuke: dangerous permissions removed').catch(()=>undefined);removed.push(role.name);}}return removed;}
async function punish(guild:Guild,executorId:string,action:string,count:number,limit:AntiNukeLimit):Promise<void>{const data=loadGuild(guild.id).antiNuke;if(isAntiNukeTrusted(guild,executorId)){await log(guild,'🛡️ Trusted Security Event',`Trusted executor <@${executorId}> attempted a protected **${action}** action. No punishment was applied.`,0x5865f2,[{name:'Activity',value:`1st action • protected`,inline:true}]);return;}const member=await guild.members.fetch(executorId).catch(()=>null);let result='Executor could not be fetched.';if(member?.bannable){await member.ban({reason:`Anti-Nuke: unauthorized ${action}`}).catch(()=>undefined);result='Executor **banned immediately**.';}else if(member){result='Executor could not be banned because of Discord role hierarchy.';}await log(guild,'🚨 Anti-Nuke • INSTANT BAN','An unauthorized destructive action was detected. The executor was checked for immediate enforcement.',0xed4245,[{name:'Executor',value:`<@${executorId}>`,inline:true},{name:'Action',value:action,inline:true},{name:'Enforcement',value:result},{name:'Protection',value:'First-action detection • no whitelist • instant ban'}]);const owner=await guild.fetchOwner().catch(()=>null);if(owner)await owner.send({embeds:[new EmbedBuilder().setColor(0xed4245).setTitle('🚨 Anti-Nuke Instant Ban').setDescription(`Anti-Nuke detected an unauthorized **${action}** action in **${guild.name}**.`).addFields({name:'Executor',value:`<@${executorId}>`},{name:'Enforcement',value:result},{name:'Protection',value:'Instant first-action ban'}).setTimestamp()]}).catch(()=>undefined);}
export async function handleAntiNukeAudit(entry:GuildAuditLogsEntry,guild:Guild):Promise<void>{const data=loadGuild(guild.id);if(!data.antiNuke.enabled)return;const action=ACTIONS[entry.action as number];if(!action)return;const executorId=entry.executorId;if(!executorId||executorId===guild.client.user?.id||isAntiNukeTrusted(guild,executorId))return;if(action==='bot_add'){await punish(guild,executorId,'unauthorized bot addition',1,{maxCount:1,windowSeconds:1});const botId=entry.targetId;if(botId){const added=await guild.members.fetch(botId).catch(()=>null);if(added?.user.bot)await added.kick('Anti-Nuke: unauthorized bot addition').catch(()=>undefined);}return;}const configured=data.antiNuke.limits[action];if(!configured)return;const limit={...configured,maxCount:1};const count=hit(`${guild.id}:${executorId}:${action}`,limit);if(count>=1)await punish(guild,executorId,action,count,limit);}
