import type { Message, BaseGuildTextChannel, GuildMember } from 'discord.js';
import { PermissionFlagsBits } from 'discord.js';
import { loadGuild, updateGuild, claimCommandMessage, claimMessageEvent } from '../storage.js';
import { levelFromXp } from '../utils.js';
import { handlePrefixCommand, getGuildPrefix } from '../prefixHandler.js';
import { handleMissingPrefixCommand } from '../prefixBridge.js';
import { handlePrefixlessMessage } from '../prefixless.js';
import { buildLevelUpEmbed } from '../commands/levelconfig.js';
import { askAI } from '../commands/ai.js';
import { getGlobalAfk, addGlobalAfkPing, removeGlobalAfk } from '../globalAfk.js';
import { buildAfkReturnPayload } from '../commands/afk.js';
import { EmbedBuilder } from 'discord.js';
import { captureCommandEmbed, applyEditableEmbed } from '../commandEmbedRegistry.js';
const spamTracker=new Map<string,number[]>(),mentionTracker=new Map<string,number[]>(),spaceTracker=new Map<string,number[]>();
function containsAutoresponderTrigger(content:string,trigger:string):boolean{const c=content.toLocaleLowerCase(),t=trigger.toLocaleLowerCase().trim();if(!t)return false;const e=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`(^|[^\\p{L}\\p{N}_])${e}($|[^\\p{L}\\p{N}_])`,'u').test(c);}
function escapeRegex(value:string):string{return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function matchesWords(content:string,words:string[]):string|undefined{const n=content.toLocaleLowerCase();for(const word of words){const w=word.trim().toLocaleLowerCase();if(!w)continue;const re=new RegExp(`(^|[^\\p{L}\\p{N}_])${escapeRegex(w)}($|[^\\p{L}\\p{N}_])`,'u');if(re.test(n))return w;}return undefined;}
function immune(message:Message):boolean{if(!message.guild||!message.member)return true;const d=loadGuild(message.guild.id);return message.author.id===message.guild.ownerId||(d.extraOwners??[]).includes(message.author.id)||(d.antiNuke?.whitelist??[]).includes(message.author.id);}
function pushWindow(map:Map<string,number[]>,key:string,seconds:number):number[]{const now=Date.now(),windowMs=Math.max(1,seconds||5)*1000,h=(map.get(key)??[]).filter(t=>now-t<windowMs);h.push(now);map.set(key,h);return h;}
function trackActivity(message:Message):void{if(!message.guild||message.author.bot)return;const guildId=message.guild.id,userId=message.author.id,now=Date.now(),day=new Date(now).toISOString().slice(0,10),month=day.slice(0,7),words=(message.content.toLocaleLowerCase().match(/[\p{L}\p{N}']+/gu)??[]).filter(w=>w.length>=4&&w.length<=32).slice(0,80);updateGuild(guildId,d=>{const a=d.activity,u=a.users[userId]??{totalMessages:0,activeDays:0,firstSeen:now,lastSeen:now,daily:{},monthly:{}};const before=u.daily[day]?.count??0;if(!u.daily[day])u.daily[day]={count:0,words:{}};u.totalMessages++;u.lastSeen=now;if(before===0)u.activeDays++;u.daily[day].count++;for(const w of words)u.daily[day].words[w]=(u.daily[day].words[w]??0)+1;u.monthly[month]=(u.monthly[month]??0)+1;a.users[userId]=u;a.totalMessages++;});}
async function punish(message:Message,reason:string,rule:any):Promise<void>{const action=rule?.action??loadGuild(message.guild!.id).config.automod?.action??'delete_timeout',d=loadGuild(message.guild!.id),template=rule?.templateId?(d.config.moderationTemplates??[]).find(x=>x.id===rule.templateId):undefined;if(action==='delete'||action==='delete_timeout'||action==='dm_warn')await message.delete().catch(()=>undefined);if(action==='warn'||action==='dm_warn'){const text=template?.message??`⚠️ Your message was removed by AutoMod: **${reason}**`;if(action==='dm_warn')await message.author.send(text).catch(()=>undefined);else await message.reply(text).catch(()=>undefined);}if(action==='timeout'||action==='delete_timeout')await message.member?.timeout(10*60*1000,`AutoMod: ${reason}`).catch(()=>undefined);}
async function runAutoMod(message:Message):Promise<boolean>{if(!message.guild||!message.member||message.author.bot||immune(message))return false;const d=loadGuild(message.guild.id),cfg=d.config.automod;if(!cfg?.enabled||message.member.permissions.has(PermissionFlagsBits.Administrator)||message.member.permissions.has(PermissionFlagsBits.ManageGuild))return false;let reason:string|undefined,rule:any;const banned=matchesWords(message.content,cfg.bannedWords??[]);if(banned){reason=`banned word: ${banned}`;rule=cfg.bannedWordsRule;}if(!reason&&cfg.antiScam){const scam=matchesWords(message.content,cfg.antiScamWords??[]);if(scam){reason=`anti-scam word: ${scam}`;rule=cfg.antiScamRule;}}if(!reason&&cfg.suspiciousLinks&&/https?:\/\/(?:discord\.gift|discordgift|free[-_ ]?nitro|nitro[-_ ]?gift|steamcommunitty|discorcl|discordapp\.gift)/i.test(message.content)){reason='suspicious link';rule=cfg.suspiciousLinksRule;}const mentionCount=message.mentions.users.size+message.mentions.roles.size;if(!reason&&cfg.massMentions&&mentionCount>0){const r=cfg.mentions??{windowSeconds:5,maxCount:3},h=pushWindow(mentionTracker,`${message.guild.id}:${message.author.id}`,r.windowSeconds??5);if(h.length>=(r.maxCount??3)||mentionCount>=(r.maxCount??3)){reason='mention spam';rule=r;}}if(!reason&&cfg.antiSpam){const r=cfg.spam??{windowSeconds:5,maxCount:6},h=pushWindow(spamTracker,`${message.guild.id}:${message.author.id}`,r.windowSeconds??6);if(h.length>=(r.maxCount??6)){reason='message spam';rule=r;}}if(!reason&&cfg.spaceSpam){const blank=message.content.split(/\r?\n/).filter(x=>!x.trim()).length,r=cfg.space??{windowSeconds:5,maxCount:5},h=blank>0?pushWindow(spaceTracker,`${message.guild.id}:${message.author.id}`,r.windowSeconds??5):[];if(blank>=(r.maxCount??5)||h.length>=(r.maxCount??5)){reason='space/dot spam';rule=r;}}if(!reason)return false;await punish(message,reason,rule);return true;}
export async function handleMessageCreate(message:Message):Promise<void>{if(message.author.bot||!message.guild||!message.member)return;const guildConfig=loadGuild(message.guild.id).config;if(guildConfig.bloxValueChannelId===message.channelId&&message.mentions.users.has(message.client.user?.id??''))return;if(!(await claimMessageEvent(message.id)))return;trackActivity(message);if(await handlePrefixlessMessage(message))return;if(await runAutoMod(message))return;const restricted=loadGuild(message.guild.id),{chatBanRole,jailRole}=restricted.config,memberRoles=message.member.roles.cache;if((chatBanRole&&memberRoles.has(chatBanRole))||(jailRole&&memberRoles.has(jailRole))){await message.delete().catch(()=>undefined);return;}const commandPrefix=getGuildPrefix(message.guild.id);
const aiConfig=loadGuild(message.guild.id).config;
const botId=message.client.user?.id;
const mentionedBot=!!botId&&message.mentions.users.has(botId);
if(aiConfig.aiChannelId===message.channelId&&mentionedBot&&!message.content.startsWith('/')&&!message.content.startsWith(commandPrefix)){
const prompt=botId?message.content.replace(new RegExp('<@!?' + botId + '>','g'),'').trim():message.content.trim();
if(prompt){
await message.channel.sendTyping().catch(()=>undefined);
const answer=await askAI(message.guild.id,message.author.id,prompt);
await message.reply({content:answer.slice(0,1900),allowedMentions:{parse:[]}}).catch(error=>console.error('[AI] Discord reply failed:',error));
return;
}
}if(message.content.startsWith(commandPrefix)){const claimed=await claimCommandMessage(message.id);if(!claimed)return;}if(await handleMissingPrefixCommand(message))return;const rawPrefix=message.content.slice(commandPrefix.length).trim();const nativeCommandName=rawPrefix.split(/\s+/)[0]?.toLowerCase()??'';const rawMessage:any=message;const originalReply=rawMessage.reply?.bind(rawMessage);const patchPrefixPayload=async(payload:any)=>{if(!payload||!message.guildId||!Array.isArray(payload.embeds))return payload;const sourceKey=nativeCommandName==='ticket'?'ticket:create':nativeCommandName==='closeticket'?'ticket:close':nativeCommandName==='reopen'?'ticket:reopen':nativeCommandName==='ticketpanel'?'ticket:panel':nativeCommandName;return {...payload,embeds:payload.embeds.map((raw:any)=>{try{const embed=raw instanceof EmbedBuilder?raw:new EmbedBuilder(raw);captureCommandEmbed(message.guildId!,nativeCommandName,embed);return applyEditableEmbed(message.guildId!,sourceKey,embed);}catch{return raw;}})};};if(originalReply)rawMessage.reply=async(payload:any)=>originalReply(await patchPrefixPayload(payload));try{await handlePrefixCommand(message);}finally{if(originalReply)rawMessage.reply=originalReply;}
const guildId=message.guild.id,userId=message.author.id,prefix=commandPrefix,trimmed=message.content.trim().toLowerCase(),isSettingAfk=trimmed===`${prefix}afk`||trimmed.startsWith(`${prefix}afk `);
const globalEntry=getGlobalAfk(userId),localEntry=loadGuild(guildId).afk[userId] as any;if((globalEntry||localEntry)&&!isSettingAfk){const pings:any[]=[];if(globalEntry){const old=await removeGlobalAfk(userId);if(old?.length)pings.push(...old);}if(localEntry?.pings?.length)pings.push(...localEntry.pings);updateGuild(guildId,d=>{delete d.afk[userId];});const member=message.member as GuildMember;if(member.nickname?.startsWith('[AFK] '))await member.setNickname(member.nickname.slice(6)||null).catch(()=>undefined);await message.reply(buildAfkReturnPayload(pings)).catch(()=>undefined);}
for(const mentioned of message.mentions.users.values()){if(mentioned.id===userId)continue;const ping={guildId:message.guild.id,guildName:message.guild.name,channelId:message.channelId,channelName:'channel' in message.channel?String((message.channel as any).name??'channel'):'channel',messageId:message.id,messageUrl:message.url,authorId:userId,authorName:message.author.globalName??message.author.username,timestamp:Date.now()};const global=getGlobalAfk(mentioned.id);if(global){await addGlobalAfkPing(mentioned.id,ping);await message.reply({content:`💤 **${mentioned.username}** is globally AFK since <t:${Math.floor(global.timestamp/1000)}:R>: ${global.reason}`}).catch(()=>undefined);continue;}const fresh=loadGuild(guildId),afkEntry=fresh.afk[mentioned.id] as any;if(afkEntry){updateGuild(guildId,d=>{const e=d.afk[mentioned.id] as any;if(e){e.pings=Array.isArray(e.pings)?e.pings:[];if(!e.pings.some((p:any)=>p.messageId===message.id))e.pings.push(ping);if(e.pings.length>100)e.pings.splice(0,e.pings.length-100);}});await message.reply({content:`💤 **${mentioned.username}** is AFK since <t:${Math.floor(afkEntry.timestamp/1000)}:R>: ${afkEntry.reason}`}).catch(()=>undefined);}}
const freshData=loadGuild(guildId);for(const ar of freshData.autoResponders){if(containsAutoresponderTrigger(message.content,ar.trigger)){await message.reply({content:ar.response}).catch(()=>undefined);break;}}
const levelCfg=freshData.config.leveling??{xpMin:15,xpMax:25,cooldownSeconds:60,multiplier:1,bonusXp:0,levelUp:{},ignoreChannels:[],ignoreRoles:[],roleRewards:{}};const ignoredChannel=levelCfg.ignoreChannels.includes(message.channelId),ignoredRole=levelCfg.ignoreRoles.some(id=>message.member!.roles.cache.has(id));const now=Date.now(),levelData=freshData.levels[userId]??{xp:0,level:0,lastMessage:0};if(!ignoredChannel&&!ignoredRole&&now-levelData.lastMessage>=Math.max(0,levelCfg.cooldownSeconds)*1000){const base=Math.floor(Math.random()*(Math.max(levelCfg.xpMin,levelCfg.xpMax)-Math.min(levelCfg.xpMin,levelCfg.xpMax)+1))+Math.min(levelCfg.xpMin,levelCfg.xpMax);const xpGain=Math.max(0,Math.floor(base*Math.max(0,levelCfg.multiplier)+Math.max(0,levelCfg.bonusXp))),oldLevel=levelData.level;levelData.xp+=xpGain;levelData.level=levelFromXp(levelData.xp);levelData.lastMessage=now;updateGuild(guildId,d=>{d.levels[userId]=levelData;});if(levelData.level>oldLevel){const guildData=loadGuild(guildId),announceCh=guildData.config.leveling?.levelUp?.channelId??guildData.config.levelChannel??message.channelId,levelRoleId=guildData.config.leveling?.roleRewards?.[String(levelData.level)]??guildData.config.levelRoles?.[String(levelData.level)];let roleName:string|undefined;if(levelRoleId){const gm=await message.guild.members.fetch(userId).catch(()=>null);if(gm){await gm.roles.add(levelRoleId).catch(()=>undefined);const role=await message.guild.roles.fetch(levelRoleId).catch(()=>null);roleName=role?.name;}}try{const ch=await message.guild.channels.fetch(announceCh);if(ch?.isTextBased()){const cfg=guildData.config.leveling?.levelUp,embed=buildLevelUpEmbed(`<@${userId}>`,levelData.level,levelData.xp,message.author.displayAvatarURL(),cfg?.title??guildData.config.levelUpMessage?.title,cfg?.description??guildData.config.levelUpMessage?.description,cfg?.imageUrl??guildData.config.levelUpMessage?.imageUrl,cfg?.color);if(roleName)embed.addFields({name:'🎖️ Role Unlocked',value:roleName,inline:true});await(ch as BaseGuildTextChannel).send({embeds:[embed],allowedMentions:{users:[userId],roles:[]}});}}catch{}}}}
