import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, type Client, type Message } from 'discord.js';
import { loadGuild, updateGuild } from './storage.js';
import { addGlobalAfkPing, getGlobalAfk, removeGlobalAfk } from './globalAfk.js';

function jumpRows(pings:any[]){const rows:ActionRowBuilder<ButtonBuilder>[]=[];for(let i=0;i<pings.length&&i<25;i+=5){const row=new ActionRowBuilder<ButtonBuilder>();for(const p of pings.slice(i,i+5))row.addComponents(new ButtonBuilder().setLabel(`Jump #${p.n}`).setStyle(ButtonStyle.Link).setURL(p.url));rows.push(row);}return rows;}
function pingOf(message:Message){return {guildId:message.guild!.id,guildName:message.guild!.name,channelId:message.channelId,channelName:'name' in message.channel?(message.channel as any).name:'channel',messageId:message.id,messageUrl:message.url,authorId:message.author.id,authorName:message.author.tag,timestamp:Date.now()};}

export function registerAfkEvents(client:Client){client.on('messageCreate',async(message:Message)=>{if(message.author.bot||!message.guild)return;const uid=message.author.id;
  const global=getGlobalAfk(uid);
  if(global){const pings=await removeGlobalAfk(uid);if(pings.length){const numbered=pings.map((p,i)=>({...p,n:i+1,url:p.messageUrl}));const embed=new EmbedBuilder().setColor(0x57F287).setTitle('👋 Welcome back!').setDescription(`You were away for <t:${Math.floor(global.timestamp/1000)}:R> and received **${numbered.length} ping${numbered.length===1?'':'s'}**.`).addFields({name:'Reason',value:global.reason});await message.reply({embeds:[embed],components:jumpRows(numbered)}).catch(()=>undefined);}return;}
  const data=loadGuild(message.guild.id);const local:any=data.afk[uid];if(local){const pings=local.pings??[];updateGuild(message.guild.id,d=>{delete (d.afk[uid] as any);});if(pings.length){const numbered=pings.map((p:any,i:number)=>({...p,n:i+1,url:p.messageUrl}));const embed=new EmbedBuilder().setColor(0x57F287).setTitle('👋 Welcome back!').setDescription(`You were away for <t:${Math.floor(local.timestamp/1000)}:R> and received **${numbered.length} ping${numbered.length===1?'':'s'}**.`).addFields({name:'Reason',value:local.reason});await message.reply({embeds:[embed],components:jumpRows(numbered)}).catch(()=>undefined);}return;}
  for(const mentioned of message.mentions.users.values()){if(mentioned.id===uid)continue;const g=getGlobalAfk(mentioned.id);if(g){await addGlobalAfkPing(mentioned.id,pingOf(message));await message.reply({content:`💤 **${mentioned.username}** is globally AFK since <t:${Math.floor(g.timestamp/1000)}:R>: ${g.reason}`}).catch(()=>undefined);continue;}const target=loadGuild(message.guild.id).afk[mentioned.id] as any;if(target){const ping=pingOf(message);updateGuild(message.guild.id,d=>{const e:any=d.afk[mentioned.id];if(e){e.pings=e.pings??[];if(!e.pings.some((p:any)=>p.messageId===ping.messageId))e.pings.push(ping);if(e.pings.length>100)e.pings.splice(0,e.pings.length-100);}});}
  }
});}
