import type { Client, Message, Attachment } from 'discord.js';
import { EmbedBuilder, Events, PermissionFlagsBits, SlashCommandBuilder } from 'discord.js';
import type { Command } from './types.js';
import { claimMessageEvent, loadGuild, updateGuild } from './storage.js';
import { BLOX_VALUES, findBloxValue } from './commands/bloxvalue.js';

type DetectedItem = { name: string; quantity?: number; permanent?: boolean; confidence?: number };
type ScanResult = { left: DetectedItem[]; right: DetectedItem[] };
type StoredScreenshot = { url: string; messageId: string; createdAt: number };
const SCAN_KEY = Symbol.for('sparxie.bloxscanner.registered');
const MAX_IMAGE_BYTES = 15 * 1024 * 1024;
const SUPPORTED_EXT = /\.(png|jpe?g|webp)$/i;
const isImage = (a: Attachment) => Boolean(a.contentType?.startsWith('image/')) || SUPPORTED_EXT.test(a.name ?? '');
const isSs = (s: string) => /^(?:\.|!)?ss$/i.test(s.trim());

function parseValue(raw: string): number | null { const m = raw.trim().toUpperCase().replace(/,/g, '').match(/^(-?\d+(?:\.\d+)?)([KMBT])?$/); if (!m) return null; const n = Number(m[1]); const mult = m[2] === 'K' ? 1e3 : m[2] === 'M' ? 1e6 : m[2] === 'B' ? 1e9 : m[2] === 'T' ? 1e12 : 1; return Number.isFinite(n) ? n * mult : null; }
function parseDemand(raw?: string): number | null { const m = String(raw ?? '').match(/(\d+(?:\.\d+)?)\s*\/\s*10/); return m ? Math.max(0, Math.min(10, Number(m[1]))) : null; }
function money(v: number): string { const a = Math.abs(v); if (!Number.isFinite(v)) return '—'; if (a >= 1e12) return `${(v / 1e12).toFixed(2).replace(/\.00$/, '')}T`; if (a >= 1e9) return `${(v / 1e9).toFixed(a >= 1e10 ? 1 : 2).replace(/\.00$/, '')}B`; if (a >= 1e6) return `${(v / 1e6).toFixed(a >= 1e8 ? 0 : 2).replace(/\.00$/, '')}M`; if (a >= 1e3) return `${(v / 1e3).toFixed(a >= 1e5 ? 0 : 1).replace(/\.0$/, '')}K`; return Math.round(v).toLocaleString('en-US'); }
function normalize(s: string): string { return s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim(); }
function resolve(item: DetectedItem) { const entry = findBloxValue(item.name); if (!entry) return null; const quantity = Math.max(1, Math.min(50, Math.round(Number(item.quantity ?? 1)))); const permanent = Boolean(item.permanent); const raw = permanent && entry.perm && entry.perm !== '—' && entry.perm !== 'N/A' ? parseValue(entry.perm) : parseValue(entry.regular); if (raw === null) return null; return { entry, quantity, permanent, unit: raw, demand: parseDemand(entry.demand), confidence: item.confidence ?? 0 }; }
function totals(items: DetectedItem[]) { const resolved: any[] = []; const unknown: string[] = []; let raw = 0, score = 0, demandSum = 0, demandCount = 0; for (const item of items) { const r = resolve(item); if (!r) { unknown.push(item.name); continue; } const value = r.unit * r.quantity; const demandMultiplier = r.demand == null ? 0.85 : 0.70 + (0.03 * r.demand); raw += value; score += value * demandMultiplier; if (r.demand != null) { demandSum += r.demand; demandCount++; } resolved.push({ ...r, value }); } return { resolved, unknown, raw, score, avgDemand: demandCount ? demandSum / demandCount : null }; }
function classify(leftScore: number, rightScore: number): { label: 'W' | 'FAIR' | 'L'; ratio: number } { if (leftScore === 0 && rightScore === 0) return { label: 'FAIR', ratio: 1 }; if (rightScore === 0) return { label: leftScore > 0 ? 'L' : 'FAIR', ratio: Infinity }; if (leftScore === 0) return { label: 'W', ratio: 0 }; const ratio = leftScore / rightScore; if (ratio >= 0.90 && ratio <= 1.10) return { label: 'FAIR', ratio }; return ratio < 1 ? { label: 'W', ratio } : { label: 'L', ratio }; }
function buildEmbed(authorId: string, result: ScanResult, sourceId: string): EmbedBuilder { const left = totals(result.left), right = totals(result.right), verdict = classify(left.score, right.score); const list = (s: ReturnType<typeof totals>) => s.resolved.length ? s.resolved.map(x => `${x.quantity > 1 ? `${x.quantity}x ` : ''}${x.entry.name}${x.permanent ? ' (Perm)' : ''} — **${money(x.value)}** · Demand **${x.demand == null ? 'N/A' : `${x.demand}/10`}**`).join('\n') : 'None detected'; const ratio = Number.isFinite(verdict.ratio) ? `${(verdict.ratio * 100).toFixed(1)}%` : '∞'; const embed = new EmbedBuilder().setTitle(`🔎 Trade Scanner — ${verdict.label}`).setColor(verdict.label === 'W' ? 0x2ecc71 : verdict.label === 'L' ? 0xe74c3c : 0xf1c40f).setDescription(`**<@${authorId}>** is the screenshot sender. **Left = their trade.** Right = the other trader.`).addFields({ name: '👈 Screenshot Sender / LEFT', value: `${list(left)}\n\n**Raw value:** ${money(left.raw)}\n**Demand-adjusted:** ${money(left.score)}\n**Average demand:** ${left.avgDemand == null ? 'N/A' : `${left.avgDemand.toFixed(1)}/10`}`.slice(0, 1024) }, { name: '👉 Other Trader / RIGHT', value: `${list(right)}\n\n**Raw value:** ${money(right.raw)}\n**Demand-adjusted:** ${money(right.score)}\n**Average demand:** ${right.avgDemand == null ? 'N/A' : `${right.avgDemand.toFixed(1)}/10`}`.slice(0, 1024) }, { name: '📊 FINAL VERDICT', value: `# **${verdict.label}**\nScore ratio: **${ratio}**\nRaw difference: **${money(left.raw - right.raw)}**\nDemand-adjusted difference: **${money(left.score - right.score)}**`, inline: false }).setFooter({ text: `Blox Fruits W/F/L Scanner • ${sourceId}` }).setTimestamp(); const unknown = [...left.unknown, ...right.unknown]; if (unknown.length) embed.addFields({ name: '⚠️ Unmatched / Not Counted', value: [...new Set(unknown)].slice(0, 10).map(x => `• ${x}`).join('\n').slice(0, 1024) }); return embed; }
async function downloadImage(url: string) { const response = await fetch(url); if (!response.ok) throw new Error(`Image download failed: ${response.status}`); const bytes = await response.arrayBuffer(); if (bytes.byteLength > MAX_IMAGE_BYTES) throw new Error('Image too large'); return { mime: response.headers.get('content-type')?.split(';')[0] || 'image/png', data: Buffer.from(bytes).toString('base64') }; }
function parseJson(text: string): ScanResult { const clean = text.trim().replace(/^```(?:json)?/i, '').replace(/```$/i, '').trim(); const start = clean.indexOf('{'), end = clean.lastIndexOf('}'); if (start < 0 || end <= start) throw new Error('Invalid vision response'); const data = JSON.parse(clean.slice(start, end + 1)) as any; const side = (v: unknown): DetectedItem[] => Array.isArray(v) ? v.map((x: any) => ({ name: typeof x?.name === 'string' ? x.name.trim() : '', quantity: Number.isFinite(Number(x?.quantity)) ? Number(x.quantity) : 1, permanent: Boolean(x?.permanent), confidence: Number.isFinite(Number(x?.confidence)) ? Number(x.confidence) : 0 })).filter(x => x.name) : []; return { left: side(data.left), right: side(data.right) }; }
const catalog = () => BLOX_VALUES.map(x => x.name).join(', ');
async function visionPass(image: { mime: string; data: string }, key: string, model: string, mode: 'layout' | 'visual'): Promise<ScanResult> { const focus = mode === 'layout' ? 'Prioritize OCR/text labels, slot boundaries, the two player name headers, and the exact left/right trade columns.' : 'Prioritize the artwork/icon in every occupied trade slot and cross-check it against the visible label; ignore hotbar/inventory icons.'; const prompt = `Deep-scan this Blox Fruits trade screenshot. ${focus}\n\nFIRST isolate the actual TRADE WINDOW in the center. The LEFT column is ALWAYS the person who uploaded the screenshot; RIGHT is the other trader. Inspect EVERY occupied slot one-by-one. Empty plus slots are not items. Ignore the bottom hotbar, inventory, abilities, background, decorative UI, and player nameplates. Use BOTH the text label and the item artwork. Handle countdown overlays such as 3/2/1 that may cover part of an item. Detect special/skin variants exactly when visible (examples: Yellow Lightning, Green Lightning, Red Lightning, Torment Pain, Meme-Meme). Detect duplicate items and quantity. Permanent=true only if clearly permanent. Never invent an item. If uncertain, return the visible/canonical name with confidence below 0.70 rather than guessing. Match names to this canonical database: ${catalog()}\n\nReturn JSON ONLY: {"left":[{"name":"canonical database name","quantity":1,"permanent":false,"confidence":0.99}],"right":[]}`; const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ contents: [{ role: 'user', parts: [{ text: prompt }, { inlineData: { mimeType: image.mime, data: image.data } }] }], generationConfig: { temperature: 0, maxOutputTokens: 1800, responseMimeType: 'application/json', candidateCount: 1 } }) }); if (!response.ok) throw new Error(`Gemini ${response.status}: ${(await response.text()).slice(0, 300)}`); const body = await response.json() as any; const text = body.candidates?.[0]?.content?.parts?.map((p: any) => p.text ?? '').join('').trim(); if (!text) throw new Error('Gemini returned no scan result'); return parseJson(text); }
function mergePasses(a: ScanResult, b: ScanResult): ScanResult { const mergeSide = (first: DetectedItem[], second: DetectedItem[]) => { const out: DetectedItem[] = []; const add = (item: DetectedItem) => { const entry = findBloxValue(item.name); if (!entry) return; const canonical = entry.name; const existing = out.find(x => normalize(x.name) === normalize(canonical)); const qty = Math.max(1, Math.min(50, Math.round(Number(item.quantity ?? 1)))); if (existing) { existing.confidence = Math.max(existing.confidence ?? 0, item.confidence ?? 0); existing.permanent = Boolean(existing.permanent || item.permanent); existing.quantity = Math.max(existing.quantity ?? 1, qty); } else out.push({ name: canonical, quantity: qty, permanent: Boolean(item.permanent), confidence: item.confidence ?? 0 }); }; for (const x of first) add(x); for (const x of second) add(x); return out; }; return { left: mergeSide(a.left, b.left), right: mergeSide(a.right, b.right) }; }
async function analyze(url: string): Promise<ScanResult> { const key = process.env.GEMINI_API_KEY?.trim(); if (!key) throw new Error('GEMINI_API_KEY is not configured'); const image = await downloadImage(url); const model = process.env.GEMINI_SCANNER_MODEL?.trim() || process.env.GEMINI_MODEL?.trim() || 'gemini-2.5-flash'; const [layout, visual] = await Promise.all([visionPass(image, key, model, 'layout'), visionPass(image, key, model, 'visual')]); return mergePasses(layout, visual); }
function latest(guildId: string, userId: string): StoredScreenshot | null { return loadGuild(guildId).config.bloxScannerScreenshots?.[userId] ?? null; }
function saveScreenshot(message: Message, attachment: Attachment) { updateGuild(message.guild!.id, data => { data.config.bloxScannerScreenshots = data.config.bloxScannerScreenshots ?? {}; data.config.bloxScannerScreenshots[message.author.id] = { url: attachment.url, messageId: message.id, createdAt: Date.now() }; }); }
async function scan(message: Message, url: string, sourceId: string) { const status = await message.reply('🔎 **Scanning screenshot...**\nDeep-identifying every trade slot, matching fruits/items to the value database, and checking demand.'); try { const result = await analyze(url); const left = totals(result.left), right = totals(result.right); if (!left.resolved.length && !right.resolved.length) { await status.edit('❌ I could not confidently identify any supported trade items. Please upload the full trade window clearly.'); return; } await status.edit({ content: '', embeds: [buildEmbed(message.author.id, result, sourceId)] }); } catch (err) { console.error('[BloxScanner]', err); const reason = err instanceof Error ? err.message : String(err); await status.edit(reason.includes('GEMINI_API_KEY') ? '❌ Scanner needs **GEMINI_API_KEY** in Render.' : '❌ Deep scan failed. Please try a clear full trade screenshot again.'); } }
export const bloxscanner: Command = { data: new SlashCommandBuilder().setName('bloxscanner').setDescription('Deep Blox Fruits W/F/L screenshot scanner').addSubcommand(s => s.setName('enable').setDescription('Enable scanner in this channel')).addSubcommand(s => s.setName('disable').setDescription('Disable scanner')).addSubcommand(s => s.setName('status').setDescription('Show scanner channel')).addSubcommand(s => s.setName('scan').setDescription('Scan your latest screenshot')), async execute(interaction) { if (!interaction.guildId) { await interaction.reply({ content: '❌ Server only.', ephemeral: true }); return; } const sub = interaction.options.getSubcommand(); if (sub === 'status') { const id = loadGuild(interaction.guildId).config.bloxScannerChannelId; await interaction.reply(id ? `🔎 Scanner: <#${id}>` : '🔎 Scanner is disabled.'); return; } const allowed = interaction.guild?.ownerId === interaction.user.id || interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild) || interaction.memberPermissions?.has(PermissionFlagsBits.Administrator); if (sub === 'enable' || sub === 'disable') { if (!allowed) { await interaction.reply({ content: '❌ Manage Server required.', ephemeral: true }); return; } updateGuild(interaction.guildId, d => { d.config.bloxScannerChannelId = sub === 'enable' ? interaction.channelId : undefined; }); await interaction.reply(sub === 'enable' ? `🔎 **Scanner enabled in <#${interaction.channelId}>.** Upload a trade screenshot and it will scan automatically.` : '🔎 **Scanner disabled.**'); return; } const channel = loadGuild(interaction.guildId).config.bloxScannerChannelId; if (channel && channel !== interaction.channelId) { await interaction.reply({ content: `❌ Use the scanner in <#${channel}>.`, ephemeral: true }); return; } const saved = latest(interaction.guildId, interaction.user.id); if (!saved) { await interaction.reply({ content: '❌ No screenshot saved yet. Upload one first.', ephemeral: true }); return; } await interaction.deferReply(); try { const result = await analyze(saved.url); await interaction.editReply({ embeds: [buildEmbed(interaction.user.id, result, saved.messageId)] }); } catch { await interaction.editReply('❌ Deep scan failed. Check GEMINI_API_KEY and try again.'); } }, };
export function registerBloxScannerEvents(client: Client) { if ((client as any)[SCAN_KEY]) return; (client as any)[SCAN_KEY] = true; client.on(Events.MessageCreate, async (message: Message) => { try { if (message.author.bot || !message.guild) return; const enabledChannel = loadGuild(message.guild.id).config.bloxScannerChannelId; if (!enabledChannel || enabledChannel !== message.channelId) return; const attachments = [...message.attachments.values()]; const image = attachments.find(isImage); if (image) { if (!(await claimMessageEvent(`bloxscanner:image:${message.id}`))) return; saveScreenshot(message, image); await scan(message, image.url, message.id); return; } if (isSs(message.content)) { if (!(await claimMessageEvent(`bloxscanner:ss:${message.id}`))) return; const saved = latest(message.guild.id, message.author.id); if (!saved) { await message.reply('❌ No screenshot saved yet. Upload a trade screenshot first.'); return; } await scan(message, saved.url, saved.messageId); } } catch (err) { console.error('[BloxScanner:event]', err); } }); }
