import type { Client, Message, Attachment, ButtonInteraction, ModalSubmitInteraction } from 'discord.js';
import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, Events, PermissionFlagsBits, SlashCommandBuilder, ModalBuilder, TextInputBuilder, TextInputStyle } from 'discord.js';
import type { Command } from './types.js';
import { claimMessageEvent, loadGuild, updateGuild } from './storage.js';
import { BLOX_VALUES, findBloxValue } from './commands/bloxvalue.js';

type DetectedItem = { name: string; quantity?: number; permanent?: boolean; confidence?: number };
type ScanResult = { left: DetectedItem[]; right: DetectedItem[] };
type StoredScreenshot = { url: string; messageId: string; createdAt: number };
type PendingScan = { result: ScanResult; authorId: string; createdAt: number };

const SCAN_KEY = Symbol.for('sparxie.bloxscanner.registered');
const MAX_IMAGE_BYTES = 15 * 1024 * 1024;
const SUPPORTED_EXT = /\.(png|jpe?g|webp)$/i;
const pending = new Map<string, PendingScan>();
const isImage = (a: Attachment) => Boolean(a.contentType?.startsWith('image/')) || SUPPORTED_EXT.test(a.name ?? '');
const isSs = (s: string) => /^(?:\.|!)?ss$/i.test(s.trim());

function parseValue(raw: string): number | null { const m = raw.trim().toUpperCase().replace(/,/g, '').match(/^(-?\d+(?:\.\d+)?)([KMBT])?$/); if (!m) return null; const n = Number(m[1]); const mult = m[2] === 'K' ? 1e3 : m[2] === 'M' ? 1e6 : m[2] === 'B' ? 1e9 : m[2] === 'T' ? 1e12 : 1; return Number.isFinite(n) ? n * mult : null; }
function parseDemand(raw?: string): number | null { const m = String(raw ?? '').match(/(\d+(?:\.\d+)?)\s*\/\s*10/); return m ? Math.max(0, Math.min(10, Number(m[1]))) : null; }
function money(v: number): string { const a = Math.abs(v); if (!Number.isFinite(v)) return '—'; if (a >= 1e12) return `${(v/1e12).toFixed(2).replace(/\.00$/,'')}T`; if (a >= 1e9) return `${(v/1e9).toFixed(2).replace(/\.00$/,'')}B`; if (a >= 1e6) return `${(v/1e6).toFixed(2).replace(/\.00$/,'')}M`; if (a >= 1e3) return `${(v/1e3).toFixed(1).replace(/\.0$/,'')}K`; return Math.round(v).toLocaleString('en-US'); }
function resolve(item: DetectedItem) { const entry = findBloxValue(item.name); if (!entry) return null; const quantity = Math.max(1, Math.min(50, Math.round(Number(item.quantity ?? 1)))); const permanent = Boolean(item.permanent); const raw = permanent && entry.perm && entry.perm !== '—' && entry.perm !== 'N/A' ? parseValue(entry.perm) : parseValue(entry.regular); if (raw === null) return null; return { entry, quantity, permanent, unit: raw, demand: parseDemand(entry.demand), confidence: item.confidence ?? 0 }; }
function totals(items: DetectedItem[]) { const resolved:any[]=[]; const unknown:string[]=[]; let raw=0,score=0,ds=0,dc=0; for(const item of items){const r=resolve(item);if(!r){unknown.push(item.name);continue;}const value=r.unit*r.quantity;const mult=r.demand==null?.85:.70+.03*r.demand;raw+=value;score+=value*mult;if(r.demand!=null){ds+=r.demand;dc++;}resolved.push({...r,value});}return{resolved,unknown,raw,score,avgDemand:dc?ds/dc:null}; }
function classify(l:number,r:number):{label:'W'|'FAIR'|'L';ratio:number}{if(l===0&&r===0)return{label:'FAIR',ratio:1};if(r===0)return{label:l>0?'L':'FAIR',ratio:Infinity};if(l===0)return{label:'W',ratio:0};const ratio=l/r;if(ratio>=.9&&ratio<=1.1)return{label:'FAIR',ratio};return ratio<1?{label:'W',ratio}:{label:'L',ratio};}
function listItems(items:DetectedItem[]){return items.length?items.map(x=>`${x.quantity&&x.quantity>1?`${x.quantity}x `:''}${x.name}${x.permanent?' (Perm)':''}`).join(', '):'None detected';}
function finalEmbed(authorId:string,result:ScanResult):EmbedBuilder{const l=totals(result.left),r=totals(result.right),v=classify(l.score,r.score);const details=(x:any)=>x.resolved.length?x.resolved.map((i:any)=>`${i.quantity>1?`${i.quantity}x `:''}${i.entry.name}${i.permanent?' (Perm)':''} — **${money(i.value)}** · Demand **${i.demand==null?'N/A':`${i.demand}/10`}**`).join('\n'):'None';return new EmbedBuilder().setTitle(`🔎 Trade Scanner — ${v.label}`).setColor(v.label==='W'?0x2ecc71:v.label==='L'?0xe74c3c:0xf1c40f).setDescription(`**<@${authorId}>** is the screenshot sender. **Left = their trade.**`).addFields({name:'👈 Your / LEFT',value:`${details(l)}\n\n**Total:** ${money(l.raw)}\n**Demand-adjusted:** ${money(l.score)}\n**Avg demand:** ${l.avgDemand==null?'N/A':`${l.avgDemand.toFixed(1)}/10`}`.slice(0,1024)},{name:'👉 Opposite / RIGHT',value:`${details(r)}\n\n**Total:** ${money(r.raw)}\n**Demand-adjusted:** ${money(r.score)}\n**Avg demand:** ${r.avgDemand==null?'N/A':`${r.avgDemand.toFixed(1)}/10`}`.slice(0,1024)},{name:'📊 FINAL ANSWER',value:`# **${v.label}**\nRatio: **${Number.isFinite(v.ratio)?(v.ratio*100).toFixed(1)+'%':'∞'}**\nRaw difference: **${money(l.raw-r.raw)}**\nDemand difference: **${money(l.score-r.score)}**`});const u=[...l.unknown,...r.unknown];if(u.length) return finalWithUnknown(arguments[0] as string,result,[...new Set(u)]);return arguments[0] as any;}
function finalWithUnknown(authorId:string,result:ScanResult,unknown:string[]):EmbedBuilder{const l=totals(result.left),r=totals(result.right),v=classify(l.score,r.score);const e=new EmbedBuilder().setTitle(`🔎 Trade Scanner — ${v.label}`).setColor(v.label==='W'?0x2ecc71:v.label==='L'?0xe74c3c:0xf1c40f).setDescription(`**<@${authorId}>** is the screenshot sender. **Left = their trade.**`).addFields({name:'👈 Your / LEFT',value:`${l.resolved.length?l.resolved.map((i:any)=>`${i.quantity>1?`${i.quantity}x `:''}${i.entry.name}${i.permanent?' (Perm)':''} — **${money(i.value)}** · Demand **${i.demand==null?'N/A':`${i.demand}/10`}**`).join('\n'):'None'}\n\n**Total:** ${money(l.raw)}\n**Demand-adjusted:** ${money(l.score)}`.slice(0,1024)},{name:'👉 Opposite / RIGHT',value:`${r.resolved.length?r.resolved.map((i:any)=>`${i.quantity>1?`${i.quantity}x `:''}${i.entry.name}${i.permanent?' (Perm)':''} — **${money(i.value)}** · Demand **${i.demand==null?'N/A':`${i.demand}/10`}**`).join('\n'):'None'}\n\n**Total:** ${money(r.raw)}\n**Demand-adjusted:** ${money(r.score)}`.slice(0,1024)},{name:'📊 FINAL ANSWER',value:`# **${v.label}**\nRatio: **${Number.isFinite(v.ratio)?(v.ratio*100).toFixed(1)+'%':'∞'}**\nDifference: **${money(l.raw-r.raw)}**`});if(unknown.length)e.addFields({name:'⚠️ Needs correction',value:unknown.slice(0,10).map(x=>`• ${x}`).join('\n')});return e;}
function guessEmbed(authorId:string,result:ScanResult){return new EmbedBuilder().setTitle('🧠 I scanned the trade — confirm my guess').setDescription(`**Left = <@${authorId}>** (screenshot sender). **Right = other trader.**\n\nClick **Correct** if these are right. If anything is wrong, click **Wrong / Edit** and correct both lists before submitting.`).addFields({name:'👈 Guessed — Your fruits/items',value:listItems(result.left).slice(0,1024)},{name:'👉 Guessed — Opposite fruits/items',value:listItems(result.right).slice(0,1024)});}
function guessRow(key:string){return new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`bloxscan:yes:${key}`).setLabel('✅ Correct — Calculate').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`bloxscan:no:${key}`).setLabel('✏️ Wrong / Edit').setStyle(ButtonStyle.Secondary));}
async function downloadImage(url:string){const r=await fetch(url);if(!r.ok)throw new Error(`Image download failed: ${r.status}`);const b=await r.arrayBuffer();if(b.byteLength>MAX_IMAGE_BYTES)throw new Error('Image too large');return{mime:r.headers.get('content-type')?.split(';')[0]||'image/png',data:Buffer.from(b).toString('base64')};}
function parseJson(text:string):ScanResult{const clean=text.trim().replace(/^```(?:json)?/i,'').replace(/```$/i,'').trim();const s=clean.indexOf('{'),e=clean.lastIndexOf('}');if(s<0||e<=s)throw new Error('Invalid vision JSON');const d=JSON.parse(clean.slice(s,e+1)) as any;const side=(v:any):DetectedItem[]=>Array.isArray(v)?v.map((x:any)=>({name:typeof x?.name==='string'?x.name.trim():'',quantity:Number.isFinite(Number(x?.quantity))?Number(x.quantity):1,permanent:Boolean(x?.permanent),confidence:Number.isFinite(Number(x?.confidence))?Number(x.confidence):0})).filter(x=>x.name):[];return{left:side(d.left),right:side(d.right)};}
async function visionPass(image:{mime:string;data:string},key:string,model:string,mode:'text'|'art'):Promise<ScanResult>{const catalog=BLOX_VALUES.map(x=>x.name).join(', ');const focus=mode==='text'?'Read every visible item name, player header, slot boundary and left/right column. Use OCR carefully.':'Inspect every occupied card artwork and cross-check it with its label. Ignore inventory/hotbar/background.';const prompt=`Deep-read this Blox Fruits trade screenshot. ${focus} The actual TRADE WINDOW is the central yellow/black panel. LEFT column is ALWAYS the screenshot sender; RIGHT is the other trader. Inspect every occupied slot one by one. Ignore all inventory, hotbar, abilities, background and decorative UI. A large countdown number may cover an item, so use the visible label and artwork around it. Identify fruits, special/skin variants and other tradeable items visible in the trade window. Count duplicates. Preserve exact special names such as Yellow Lightning, Green Lightning, Red Lightning and Torment Pain when visible. Use this canonical catalog to match names: ${catalog}. If a name is partly obscured, choose the most likely catalog name but set confidence below 0.70. Never include an item from outside the trade window. Return JSON ONLY: {"left":[{"name":"Kitsune","quantity":1,"permanent":false,"confidence":0.99}],"right":[]}. Do not calculate W/F/L.`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt},{inlineData:{mimeType:image.mime,data:image.data}}]}],generationConfig:{temperature:0,maxOutputTokens:1800,responseMimeType:'application/json'}})});if(!r.ok)throw new Error(`Gemini ${r.status}: ${(await r.text()).slice(0,200)}`);const body=await r.json() as any;const text=body.candidates?.[0]?.content?.parts?.map((p:any)=>p.text??'').join('').trim();if(!text)throw new Error('Gemini returned no result');return parseJson(text);}
function merge(a:ScanResult,b:ScanResult):ScanResult{const side=(x:DetectedItem[],y:DetectedItem[])=>{const out:DetectedItem[]=[];for(const item of [...x,...y]){const e=findBloxValue(item.name);if(!e)continue;const existing=out.find(z=>z.name===e.name);const q=Math.max(1,Math.min(50,Math.round(Number(item.quantity??1))));if(existing){existing.quantity=Math.max(existing.quantity??1,q);existing.confidence=Math.max(existing.confidence??0,item.confidence??0);existing.permanent=Boolean(existing.permanent||item.permanent);}else out.push({name:e.name,quantity:q,permanent:Boolean(item.permanent),confidence:item.confidence??0});}return out;};return{left:side(a.left,b.left),right:side(a.right,b.right)};}
async function analyze(url:string){const key=process.env.GEMINI_API_KEY?.trim();if(!key)throw new Error('GEMINI_API_KEY is not configured');const image=await downloadImage(url);const model=process.env.GEMINI_SCANNER_MODEL?.trim()||process.env.GEMINI_MODEL?.trim()||'gemini-2.5-flash';const [a,b]=await Promise.all([visionPass(image,key,model,'text'),visionPass(image,key,model,'art')]);return merge(a,b);}
function latest(guildId:string,userId:string):StoredScreenshot|null{return loadGuild(guildId).config.bloxScannerScreenshots?.[userId]??null;}
function saveScreenshot(message:Message,attachment:Attachment){updateGuild(message.guild!.id,d=>{d.config.bloxScannerScreenshots=d.config.bloxScannerScreenshots??{};d.config.bloxScannerScreenshots[message.author.id]={url:attachment.url,messageId:message.id,createdAt:Date.now()};});}
async function scan(message:Message,url:string,sourceId:string){const status=await message.reply('🔎 **Scanning screenshot...**\nDeep-identifying every trade slot and matching fruits/items to the value + demand database.');try{const result=await analyze(url);if(!result.left.length&&!result.right.length){await status.edit('❌ I could not identify the trade items. Please upload the full trade window clearly.');return;}const key=status.id;pending.set(key,{result,authorId:message.author.id,createdAt:Date.now()});setTimeout(()=>pending.delete(key),10*60*1000).unref?.();await status.edit({content:'',embeds:[guessEmbed(message.author.id,result)],components:[guessRow(key)]});}catch(err){console.error('[BloxScanner]',err);const reason=err instanceof Error?err.message:String(err);await status.edit(reason.includes('GEMINI_API_KEY')?'❌ Scanner needs **GEMINI_API_KEY** in Render.':'❌ Deep scan failed. Please try the full trade screenshot again.');}}
function parseEdited(raw:string):DetectedItem[]{return raw.split(/[,\n]+/).map(x=>x.trim()).filter(Boolean).filter(x=>!/^none detected$/i.test(x)).map(x=>{const m=x.match(/^(\d+)\s*x\s*(.+)$/i);const permanent=/\bperm(?:anent)?\b/i.test(x);const name=(m?.[2]??x).replace(/\s*\(perm(?:anent)?\)\s*$/i,'').trim();return{name,quantity:m?Number(m[1]):1,permanent};});}
async function scannerButton(i:ButtonInteraction){const [p,a,key]=i.customId.split(':');if(p!=='bloxscan')return;const state=pending.get(key);if(!state){await i.reply({content:'❌ This scan expired. Upload the screenshot again.',ephemeral:true});return;}if(i.user.id!==state.authorId){await i.reply({content:'❌ Only the screenshot uploader can confirm/edit this scan.',ephemeral:true});return;}if(a==='yes'){await i.update({content:'',embeds:[finalEmbed(state.authorId,state.result)],components:[]});pending.delete(key);return;}if(a==='no'){const modal=new ModalBuilder().setCustomId(`bloxscanedit:${key}`).setTitle('Correct the guessed trade');const left=new TextInputBuilder().setCustomId('left').setLabel('Your fruits / items').setStyle(TextInputStyle.Paragraph).setRequired(true).setValue(listItems(state.result.left).slice(0,4000));const right=new TextInputBuilder().setCustomId('right').setLabel('Opposite fruits / items').setStyle(TextInputStyle.Paragraph).setRequired(false);const rv=listItems(state.result.right);if(rv!=='None detected')right.setValue(rv.slice(0,4000));modal.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(left),new ActionRowBuilder<TextInputBuilder>().addComponents(right));await i.showModal(modal);}}
async function scannerEdit(i:ModalSubmitInteraction){if(!i.customId.startsWith('bloxscanedit:'))return;const key=i.customId.slice('bloxscanedit:'.length),state=pending.get(key);if(!state){await i.reply({content:'❌ This scan expired. Upload the screenshot again.',ephemeral:true});return;}if(i.user.id!==state.authorId){await i.reply({content:'❌ Only the screenshot uploader can submit corrections.',ephemeral:true});return;}const result={left:parseEdited(i.fields.getTextInputValue('left')),right:parseEdited(i.fields.getTextInputValue('right'))};if(!result.left.length&&!result.right.length){await i.reply({content:'❌ Enter at least one item.',ephemeral:true});return;}await i.reply({content:'✅ **Corrected trade submitted. Final W/F/L:**',embeds:[finalEmbed(state.authorId,result)]});pending.delete(key);}
export const bloxscanner:Command={data:new SlashCommandBuilder().setName('bloxscanner').setDescription('Deep Blox Fruits W/F/L screenshot scanner').addSubcommand(s=>s.setName('enable').setDescription('Enable scanner in this channel')).addSubcommand(s=>s.setName('disable').setDescription('Disable scanner')).addSubcommand(s=>s.setName('status').setDescription('Show scanner channel')).addSubcommand(s=>s.setName('scan').setDescription('Scan your latest screenshot')),async execute(interaction){if(!interaction.guildId){await interaction.reply({content:'❌ Server only.',ephemeral:true});return;}const sub=interaction.options.getSubcommand();if(sub==='status'){const id=loadGuild(interaction.guildId).config.bloxScannerChannelId;await interaction.reply(id?`🔎 Scanner: <#${id}>`:'🔎 Scanner is disabled.');return;}const allowed=interaction.guild?.ownerId===interaction.user.id||interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild)||interaction.memberPermissions?.has(PermissionFlagsBits.Administrator);if(sub==='enable'||sub==='disable'){if(!allowed){await interaction.reply({content:'❌ Manage Server required.',ephemeral:true});return;}updateGuild(interaction.guildId,d=>{d.config.bloxScannerChannelId=sub==='enable'?interaction.channelId:undefined;});await interaction.reply(sub==='enable'?`🔎 **Scanner enabled in <#${interaction.channelId}>.** Upload a screenshot and it will scan automatically.`:'🔎 **Scanner disabled.**');return;}const channel=loadGuild(interaction.guildId).config.bloxScannerChannelId;if(channel&&channel!==interaction.channelId){await interaction.reply({content:`❌ Use the scanner in <#${channel}>.`,ephemeral:true});return;}const saved=latest(interaction.guildId,interaction.user.id);if(!saved){await interaction.reply({content:'❌ No screenshot saved yet. Upload one first.',ephemeral:true});return;}await interaction.deferReply();try{const result=await analyze(saved.url);const key=`manual:${interaction.id}`;pending.set(key,{result,authorId:interaction.user.id,createdAt:Date.now()});setTimeout(()=>pending.delete(key),10*60*1000).unref?.();await interaction.editReply({embeds:[guessEmbed(interaction.user.id,result)],components:[guessRow(key)]});}catch{await interaction.editReply('❌ Deep scan failed. Check GEMINI_API_KEY and try again.');}},};
export function registerBloxScannerEvents(client:Client){if((client as any)[SCAN_KEY])return;(client as any)[SCAN_KEY]=true;client.on(Events.InteractionCreate,async interaction=>{try{if(interaction.isButton())await scannerButton(interaction);else if(interaction.isModalSubmit())await scannerEdit(interaction);}catch(err){console.error('[BloxScanner interaction]',err);}});client.on(Events.MessageCreate,async(message:Message)=>{try{if(message.author.bot||!message.guild)return;const enabled=loadGuild(message.guild.id).config.bloxScannerChannelId;if(!enabled||enabled!==message.channelId)return;const attachment=[...message.attachments.values()].find(isImage);if(attachment){if(!(await claimMessageEvent(`bloxscanner:image:${message.id}`)))return;saveScreenshot(message,attachment);await scan(message,attachment.url,message.id);return;}if(isSs(message.content)){if(!(await claimMessageEvent(`bloxscanner:ss:${message.id}`)))return;const saved=latest(message.guild.id,message.author.id);if(!saved){await message.reply('❌ No screenshot saved for you. Upload a trade screenshot first.');return;}await scan(message,saved.url,saved.messageId);}}catch(err){console.error('[BloxScanner message]',err);}});}
