export const ROASTS: string[] = [
  "you're the human equivalent of a participation trophy.",
  "I'd roast you, but my mom said I'm not allowed to burn trash.",
  "You're like a cloud — when you disappear, it's a beautiful day.",
  "You bring everyone so much joy... when you leave the room.",
  "If brains were gasoline, you wouldn't have enough to power a mosquito's motorcycle around the inside of a Cheerio.",
  "You're not stupid — you just have bad luck thinking.",
  "I'd agree with you, but then we'd both be wrong.",
  "You're the reason they put instructions on shampoo bottles.",
  "Your secrets are safe with me. I wasn't even listening.",
  "I'd call you a tool, but even tools are useful.",
  "You're like a software update — whenever I see you, I think 'not now'.",
  "You have your entire life to be an idiot. Why not take today off?",
  "I've seen better-looking heads on a glass of beer.",
  "Some people are like pennies: two-faced and not worth much.",
  "You're not the dumbest person in the world, but you better hope they don't die.",
  "I'd insult you, but the sad truth is that you wouldn't understand.",
  "If laughter is the best medicine, your face must be curing the world.",
  "You're so dense, light bends around you.",
  "I'd explain it to you, but I don't have any crayons with me.",
  "You're like a broken pencil — pointless.",
  "Somewhere out there is a tree tirelessly producing oxygen for you. You owe it an apology.",
  "You're proof that evolution can go in reverse.",
  "I'm jealous of everyone who has never met you.",
  "You're the reason the gene pool needs a lifeguard.",
  "You're so boring, you make sleeping look exciting.",
  "Your wifi password must be 'incorrect' — because that's all you are.",
  "You're a gray sprinkle on a rainbow cupcake.",
  "You have miles and miles of running room before you need to stop and think.",
  "Even your reflection thinks twice before looking back at you.",
  "You're like a Monday — nobody's happy to see you, and you ruin everything.",
];
