import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { GuildData, SnipedMessage } from './types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data');
const defaultCategories = { messageDelete:true, messageEdit:true, messageBulkDelete:true, serverChanges:true, channelChanges:true, roleChanges:true, memberChanges:true, moderation:true, joinsLeaves:true, invites:true, commands:true, automod:true, giveaways:true };
function defaultGuildData(): GuildData { return { config: { starboardThreshold:3, snipeEnabled:true, levelRoles:{}, inviteRoles:{}, automod:{ enabled:false, antiSpam:false, antiScam:false, massMentions:false, suspiciousLinks:false, spaceSpam:false, bannedWords:[], antiScamWords:[], action:'delete_timeout', spam:{windowSeconds:5,maxCount:6,action:'delete_timeout'}, mentions:{windowSeconds:5,maxCount:3,action:'delete_timeout'}, space:{windowSeconds:5,maxCount:5,action:'delete_timeout'}, bannedWordsRule:{action:'delete_timeout'}, antiScamRule:{action:'delete_timeout'}, suspiciousLinksRule:{action:'delete_timeout'} }, moderationTemplates:[], logging:{enabled:false,categories:defaultCategories}, giveawayDaily:{enabled:false,message:'🎁 Don’t forget to enter our active giveaway!'} }, antiNuke:{enabled:false,whitelist:[]}, extraOwners:[], afk:{}, levels:{}, sparks:{}, warnings:{}, reminders:[], starboard:{}, lastDeleted:{}, lastEdited:{}, tempRoles:[], tickets:{}, autoResponders:[], giveaways:[], savedEmbeds:{}, shop:{roles:[],colours:[],customRoles:[]}, recoveryBackups:[] }; }
function ensureDir():void{if(!existsSync(DATA_DIR))mkdirSync(DATA_DIR,{recursive:true});}
function getFilePath(guildId:string):string{return join(DATA_DIR,`${guildId}.json`);}
function migrateSnipeField(field:Record<string,SnipedMessage|SnipedMessage[]|unknown>):Record<string,SnipedMessage[]>{const result:Record<string,SnipedMessage[]>={};for(const [channelId,value] of Object.entries(field)){if(Array.isArray(value))result[channelId]=value as SnipedMessage[];else if(value&&typeof value==='object'&&'authorId' in value)result[channelId]=[value as SnipedMessage];}return result;}
export function loadGuild(guildId:string):GuildData{ensureDir();const path=getFilePath(guildId);if(!existsSync(path))return defaultGuildData();try{const parsed=JSON.parse(readFileSync(path,'utf-8')) as Partial<GuildData>;const defaults=defaultGuildData();const old=parsed.config?.automod as any;const automod={...defaults.config.automod,...(old??{}),bannedWords:old?.bannedWords??[],antiScamWords:old?.antiScamWords??[]};const data:GuildData={...defaults,...parsed,config:{...defaults.config,...parsed.config,levelRoles:parsed.config?.levelRoles??{},inviteRoles:parsed.config?.inviteRoles??{},automod,moderationTemplates:parsed.config?.moderationTemplates??[],logging:{...defaults.config.logging,...(parsed.config?.logging??{}),categories:{...defaultCategories,...(parsed.config?.logging?.categories??{})}},giveawayDaily:{...defaults.config.giveawayDaily,...(parsed.config?.giveawayDaily??{})}},antiNuke:{...defaults.antiNuke,...(parsed.antiNuke??{}),whitelist:parsed.antiNuke?.whitelist??[]},extraOwners:parsed.extraOwners??[],sparks:parsed.sparks??{},autoResponders:parsed.autoResponders??[],giveaways:parsed.giveaways??[],savedEmbeds:parsed.savedEmbeds??{},shop:{...defaults.shop,...(parsed.shop??{}),roles:parsed.shop?.roles??[],colours:parsed.shop?.colours??[],customRoles:parsed.shop?.customRoles??[]},recoveryBackups:parsed.recoveryBackups??[]};if(parsed.lastDeleted)data.lastDeleted=migrateSnipeField(parsed.lastDeleted as any);if(parsed.lastEdited)data.lastEdited=migrateSnipeField(parsed.lastEdited as any);return data;}catch{return defaultGuildData();}}
export function saveGuild(guildId:string,data:GuildData):void{ensureDir();writeFileSync(getFilePath(guildId),JSON.stringify(data,null,2),'utf-8');}
export function updateGuild(guildId:string,updater:(data:GuildData)=>void):void{const data=loadGuild(guildId);updater(data);saveGuild(guildId,data);}
