import { EmbedBuilder, type GuildMember } from 'discord.js';
import type { SavedEmbed } from './types.js';
export function resolveVariables(text:string,member:GuildMember):string{return text.replace(/\{user\}/g,`<@${member.id}>`).replace(/\{user\.name\}/g,member.user.username).replace(/\{user\.tag\}/g,member.user.tag).replace(/\{user\.id\}/g,member.id).replace(/\{server\}/g,member.guild.name).replace(/\{membercount\}/g,String(member.guild.memberCount)).replace(/\{ordinal\}/g,toOrdinal(member.guild.memberCount));}
function resolveUrl(url:string,member:GuildMember):string|undefined{if(url==='{user.avatar}')return member.user.displayAvatarURL({size:256});if(url==='{server.icon}')return member.guild.iconURL()??undefined;return url||undefined;}
function toOrdinal(n:number):string{const s=['th','st','nd','rd'],v=n%100;return n+(s[(v-20)%10]||s[v]||s[0]);}
export function buildEmbedFromSaved(saved:SavedEmbed,member:GuildMember):EmbedBuilder{const e=new EmbedBuilder();if(saved.color!==undefined)e.setColor(saved.color);if(saved.title)e.setTitle(resolveVariables(saved.title,member).slice(0,256));if(saved.description)e.setDescription(resolveVariables(saved.description,member).slice(0,4096));if(saved.thumbnailUrl){const u=resolveUrl(saved.thumbnailUrl,member);if(u)e.setThumbnail(u);}if(saved.imageUrl){const u=resolveUrl(saved.imageUrl,member);if(u)e.setImage(u);}if(saved.footerText)e.setFooter({text:resolveVariables(saved.footerText,member).slice(0,2048),iconURL:saved.footerIconUrl?resolveUrl(saved.footerIconUrl,member):undefined});if(saved.authorName)e.setAuthor({name:resolveVariables(saved.authorName,member).slice(0,256),iconURL:saved.authorIconUrl?resolveUrl(saved.authorIconUrl,member):undefined});if(saved.fields?.length)e.addFields(saved.fields.slice(0,25).map(f=>({name:(resolveVariables(f.name,member)||'\u200b').slice(0,256),value:(resolveVariables(f.value,member)||'\u200b').slice(0,1024),inline:f.inline??false})));if(saved.timestamp!==false)e.setTimestamp();return e;}
export function buildEmbedPreview(saved:SavedEmbed):EmbedBuilder{const r=(t:string)=>t.replace(/\{user\}/g,'@NewMember').replace(/\{user\.name\}/g,'NewMember').replace(/\{user\.tag\}/g,'NewMember#0000').replace(/\{user\.id\}/g,'123456789').replace(/\{server\}/g,'Your Server').replace(/\{membercount\}/g,'100').replace(/\{ordinal\}/g,'100th');const e=new EmbedBuilder();if(saved.color!==undefined)e.setColor(saved.color);if(saved.title)e.setTitle(r(saved.title).slice(0,256));if(saved.description)e.setDescription(r(saved.description).slice(0,4096));if(saved.thumbnailUrl&&saved.thumbnailUrl!=='{user.avatar}'&&saved.thumbnailUrl!=='{server.icon}')e.setThumbnail(saved.thumbnailUrl);if(saved.imageUrl&&saved.imageUrl!=='{user.avatar}'&&saved.imageUrl!=='{server.icon}')e.setImage(saved.imageUrl);if(saved.footerText)e.setFooter({text:r(saved.footerText).slice(0,2048),iconURL:saved.footerIconUrl&&saved.footerIconUrl!=='{user.avatar}'&&saved.footerIconUrl!=='{server.icon}'?saved.footerIconUrl:undefined});if(saved.authorName)e.setAuthor({name:r(saved.authorName).slice(0,256),iconURL:saved.authorIconUrl&&saved.authorIconUrl!=='{user.avatar}'&&saved.authorIconUrl!=='{server.icon}'?saved.authorIconUrl:undefined});if(saved.fields?.length)e.addFields(saved.fields.slice(0,25).map(f=>({name:(r(f.name)||'\u200b').slice(0,256),value:(r(f.value)||'\u200b').slice(0,1024),inline:f.inline??false})));if(saved.timestamp!==false)e.setTimestamp();return e;}
export function buildWelcomeEmbed(cfg:import('./types.js').WelcomeEmbed,member:GuildMember):EmbedBuilder{const e=new EmbedBuilder();if(cfg.color!==undefined)e.setColor(cfg.color);if(cfg.title)e.setTitle(resolveVariables(cfg.title,member).slice(0,256));if(cfg.description)e.setDescription(resolveVariables(cfg.description,member).slice(0,4096));if(cfg.thumbnailUrl){const u=resolveUrl(cfg.thumbnailUrl,member);if(u)e.setThumbnail(u);}if(cfg.imageUrl){const u=resolveUrl(cfg.imageUrl,member);if(u)e.setImage(u);}if(cfg.footerText)e.setFooter({text:resolveVariables(cfg.footerText,member).slice(0,2048)});return e;}
export function buildWelcomeEmbedPreview(cfg:import('./types.js').WelcomeEmbed):EmbedBuilder{const r=(t:string)=>t.replace(/\{user\}/g,'@NewMember').replace(/\{user\.name\}/g,'NewMember').replace(/\{user\.tag\}/g,'NewMember#0000').replace(/\{user\.id\}/g,'123456789').replace(/\{server\}/g,'Your Server').replace(/\{membercount\}/g,'100').replace(/\{ordinal\}/g,'100th');const e=new EmbedBuilder();if(cfg.color!==undefined)e.setColor(cfg.color);if(cfg.title)e.setTitle(r(cfg.title).slice(0,256));if(cfg.description)e.setDescription(r(cfg.description).slice(0,4096));if(cfg.thumbnailUrl&&cfg.thumbnailUrl!=='{user.avatar}'&&cfg.thumbnailUrl!=='{server.icon}')e.setThumbnail(cfg.thumbnailUrl);if(cfg.imageUrl&&cfg.imageUrl!=='{user.avatar}'&&cfg.imageUrl!=='{server.icon}')e.setImage(cfg.imageUrl);if(cfg.footerText)e.setFooter({text:r(cfg.footerText).slice(0,2048)});return e;}
export const DEFAULT_WELCOME_MESSAGE='Welcome {user}';
export function resolveWelcomeSend(w:import('./types.js').WelcomeConfig,member:GuildMember,savedEmbeds:Record<string,import('./types.js').SavedEmbed>):{content:string|undefined;embeds:EmbedBuilder[]}{const raw=w.message??DEFAULT_WELCOME_MESSAGE;if(w.embed?.enabled&&w.embed)return{content:resolveVariables(raw,member),embeds:[buildWelcomeEmbed(w.embed,member)]};const embedName=extractEmbedName(raw);if(embedName){const saved=savedEmbeds[embedName.toLowerCase()];if(saved){const extra=raw.replace(/\{embed:[^}]+\}/i,'').trim();return{content:extra?resolveVariables(extra,member):undefined,embeds:[buildEmbedFromSaved(saved,member)]}}}return{content:resolveVariables(raw,member),embeds:[]};}
export function parseColor(hex:string):number|undefined{const n=parseInt(hex.replace('#',''),16);return isNaN(n)||n<0||n>0xFFFFFF?undefined:n;}
export function extractEmbedName(message:string):string|null{const m=message.match(/^\{embed:(.+)\}$/i);return m?m[1].trim():null;}
export const VARIABLES_HELP='`{user}` · `{user.name}` · `{user.tag}` · `{user.id}` · `{server}` · `{membercount}` · `{ordinal}`\nURL fields also accept: `{user.avatar}` · `{server.icon}`';
