import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, ModalBuilder, PermissionFlagsBits, SlashCommandBuilder, StringSelectMenuBuilder, TextInputBuilder, TextInputStyle, type CommandInteraction } from 'discord.js';
import type { Command } from '../types.js';
import { allEmojiEntries, emojiNameForBlox, refreshBloxApplicationEmojis } from '../bloxEmojiManager.js';
import { BLOX_VALUES } from './bloxvalue.js';
import { loadGuild, updateGuild } from '../storage.js';
const PAGE_SIZE=20;
const idFor=(kind:string,page:number,user:string)=>`bloxemoji:${kind}:${page}:${user}`;
const ownerIds=()=>new Set([process.env.OWNER_USER_ID??'',...(process.env.OWNER_USER_IDS??'').split(/[\s,]+/),'1405884975860940854'].map(x=>x.trim()).filter(Boolean));
function canManage(i:any){return ownerIds().has(i.user.id)||Boolean(i.memberPermissions?.has(PermissionFlagsBits.ManageGuildExpressions)||i.memberPermissions?.has(PermissionFlagsBits.ManageGuild));}
function pages(){return Math.max(1,Math.ceil(allEmojiEntries().length/PAGE_SIZE));}
function normalizeEmoji(raw:string){const s=raw.trim();if(/^<a?:[A-Za-z0-9_]+:\d{5,25}>$/.test(s))return s;const m=s.match(/^(a?:)?([A-Za-z0-9_]+):(\d{5,25})$/);if(m)return `${m[1]==='a:'?'<a:':'<:'}${m[2]}:${m[3]}>`;return null;}
function components(page:number,user:string){const list=allEmojiEntries(),total=pages(),slice=list.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);const select=new StringSelectMenuBuilder().setCustomId(idFor('pick',page,user)).setPlaceholder(`Choose fruit / skin / gamepass • ${page+1}/${total}`).addOptions(slice.map((e,i)=>({label:e.name.slice(0,100),value:String(page*PAGE_SIZE+i),description:`${e.rarity} • ${e.regular}`.slice(0,100)})));const row=new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(select);const nav=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(idFor('prev',page,user)).setLabel('◀ Prev').setStyle(ButtonStyle.Secondary).setDisabled(page===0),new ButtonBuilder().setCustomId(idFor('next',page,user)).setLabel('Next ▶').setStyle(ButtonStyle.Secondary).setDisabled(page>=total-1));return [row,nav];}
function panel(page:number){return new EmbedBuilder().setTitle('🧩 Blox Value Emoji Setup').setDescription(`Pick an item below, then paste its application emoji **name or full emoji**.\n\nRecommended application name: **bf_kitsune**\nFull emoji: <:bf_kitsune:123456789012345678>\n\nApplication emojis are supported directly; the bot does not require the emoji to be uploaded to the current server.\n\nPage ${page+1}/${pages()} • ${allEmojiEntries().length} supported entries.`);}
export const bloxemoji:Command={data:new SlashCommandBuilder().setName('bloxemoji').setDescription('Configure Discord application emojis for Blox value replies').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuildExpressions).addSubcommand(s=>s.setName('set').setDescription('Choose an item and assign an application emoji')).addSubcommand(s=>s.setName('sync').setDescription('Automatically link matching bf_* application emojis')).addSubcommand(s=>s.setName('list').setDescription('List configured Blox emojis')).addSubcommand(s=>s.setName('clear').setDescription('Clear an item emoji').addStringOption(o=>o.setName('item').setDescription('Exact item name').setRequired(true))),async execute(interaction:CommandInteraction&any){if(!interaction.guildId){await interaction.reply({content:'❌ Server only.',ephemeral:true});return;}if(!canManage(interaction)){await interaction.reply({content:'❌ You need Manage Expressions.',ephemeral:true});return;}const sub=interaction.options.getSubcommand();if(sub==='set'){await interaction.reply({embeds:[panel(0)],components:components(0,interaction.user.id),ephemeral:true});return;}const application=await interaction.client.application.fetch();const appEmojis=await application.emojis.fetch();if(sub==='sync'){let linked=0;const missing:string[]=[];updateGuild(interaction.guildId,g=>{g.config.bloxValueEmojis??={};for(const entry of allEmojiEntries()){const emoji=appEmojis.find(e=>e.name===emojiNameForBlox(entry.name));if(emoji){g.config.bloxValueEmojis[entry.name]=emoji.toString();linked++;}else missing.push(entry.name);}});await refreshBloxApplicationEmojis(interaction.client);await interaction.reply({content:`✅ **Blox application emoji sync complete.**\n\n🔗 Linked: **${linked}**\n⚠️ Missing: **${missing.length}**${missing.length?`\n\nFirst missing: ${missing.slice(0,12).join(', ')}`:''}`,ephemeral:true});return;}const cfg=loadGuild(interaction.guildId).config.bloxValueEmojis??{};if(sub==='list'){const lines=Object.entries(cfg).map(([name,emoji])=>`${emoji} **${name}**`);await interaction.reply({content:lines.length?lines.slice(0,50).join('\n'):'No Blox emojis configured yet.',ephemeral:true});return;}const entry=BLOX_VALUES.find(e=>e.name.toLowerCase()===interaction.options.getString('item',true).toLowerCase());if(!entry){await interaction.reply({content:'❌ Item not found. Use /bloxemoji set.',ephemeral:true});return;}updateGuild(interaction.guildId,g=>{g.config.bloxValueEmojis??={};delete g.config.bloxValueEmojis[entry.name];});await interaction.reply({content:`✅ Cleared ${entry.name} emoji.`,ephemeral:true});}};
export async function handleBloxEmojiInteraction(interaction:any){const raw=String(interaction.customId??'');if(!raw.startsWith('bloxemoji:'))return false;const parts=raw.split(':'),kind=parts[1],page=Math.max(0,Number(parts[2])||0),user=parts[3];if(user!==interaction.user.id){await interaction.reply({content:'❌ This setup menu belongs to another user.',ephemeral:true}).catch(()=>{});return true;}if(kind==='prev'||kind==='next'){const next=Math.max(0,Math.min(pages()-1,kind==='next'?page+1:page-1));await interaction.update({embeds:[panel(next)],components:components(next,user)});return true;}if(kind==='pick'){const index=Number(interaction.values?.[0]),entry=allEmojiEntries()[index];if(!entry){await interaction.reply({content:'❌ Item not found.',ephemeral:true});return true;}const modal=new ModalBuilder().setCustomId(`bloxemoji:modal:${index}:${user}`).setTitle(`Emoji • ${entry.name.slice(0,35)}`),input=new TextInputBuilder().setCustomId('emoji').setLabel('Paste app emoji name or full emoji').setPlaceholder(`bf_${entry.name.toLowerCase().replace(/[^a-z0-9]+/g,'_')} or <:bf_item:123...>`).setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100);modal.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(input));await interaction.showModal(modal);return true;}return true;}
export async function handleBloxEmojiModal(interaction:any){const raw=String(interaction.customId??'');if(!raw.startsWith('bloxemoji:modal:'))return false;const parts=raw.split(':'),index=Number(parts[2]),user=parts[3];if(user!==interaction.user.id){await interaction.reply({content:'❌ This setup belongs to another user.',ephemeral:true});return true;}if(!canManage(interaction)){await interaction.reply({content:'❌ You need Manage Expressions.',ephemeral:true});return true;}const entry=allEmojiEntries()[index];if(!entry){await interaction.reply({content:'❌ Item not found.',ephemeral:true});return true;}const rawEmoji=interaction.fields.getTextInputValue('emoji').trim();const application=await interaction.client.application.fetch();const appEmojis=await application.emojis.fetch();let emoji=normalizeEmoji(rawEmoji);if(!emoji){const byName=appEmojis.find(e=>e.name?.toLowerCase()===rawEmoji.toLowerCase());if(byName)emoji=byName.toString();}else{const idMatch=emoji.match(/^<a?:[^:]+:(\d+)>$/);if(idMatch&&!appEmojis.has(idMatch[1]))emoji=null;}if(!emoji){await interaction.reply({content:'❌ Application emoji not found. Paste its full emoji or exact application emoji name (for example `bf_kitsune`).',ephemeral:true});return true;}updateGuild(interaction.guildId,g=>{g.config.bloxValueEmojis??={};g.config.bloxValueEmojis[entry.name]=emoji!;});await refreshBloxApplicationEmojis(interaction.client);await interaction.reply({content:`✅ Set ${emoji} **${entry.name}** using the bot application emoji.`,ephemeral:true});return true;}
