import { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } from 'discord.js';
import type { Command } from '../types.js';
import { loadGuild, updateGuild } from '../storage.js';
import { buildEmbedPreview, parseColor } from '../welcomeUtils.js';
import { buildEmbedEditorSelection } from '../embedEditor.js';


export const embedCmd: Command = {
  data:new SlashCommandBuilder().setName('embed').setDescription('Create and manage reusable custom embeds').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
    .addSubcommand(s=>s.setName('create').setDescription('Create a saved embed').addStringOption(o=>o.setName('name').setDescription('Saved embed name').setRequired(true).setMaxLength(32)).addStringOption(o=>o.setName('title').setDescription('Title').setMaxLength(256)).addStringOption(o=>o.setName('description').setDescription('Description').setMaxLength(4000)).addStringOption(o=>o.setName('color').setDescription('Hex color')).addStringOption(o=>o.setName('author').setDescription('Author name').setMaxLength(256)).addStringOption(o=>o.setName('author_icon').setDescription('Author icon URL or {user.avatar}')).addStringOption(o=>o.setName('thumbnail').setDescription('Thumbnail URL or {user.avatar}/{server.icon}')).addStringOption(o=>o.setName('image').setDescription('Main image URL')).addStringOption(o=>o.setName('footer').setDescription('Footer text').setMaxLength(2048)).addStringOption(o=>o.setName('footer_icon').setDescription('Footer icon URL or {server.icon}')).addBooleanOption(o=>o.setName('timestamp').setDescription('Show timestamp (default: true)')))
    .addSubcommand(s=>s.setName('edit').setDescription('Edit a saved embed').addStringOption(o=>o.setName('name').setDescription('Embed name').setRequired(true).setAutocomplete(true)).addStringOption(o=>o.setName('title').setDescription('New title').setMaxLength(256)).addStringOption(o=>o.setName('description').setDescription('New description').setMaxLength(4000)).addStringOption(o=>o.setName('color').setDescription('New hex color')).addStringOption(o=>o.setName('author').setDescription('New author name').setMaxLength(256)).addStringOption(o=>o.setName('author_icon').setDescription('New author icon URL')).addStringOption(o=>o.setName('thumbnail').setDescription('New thumbnail URL')).addStringOption(o=>o.setName('image').setDescription('New image URL')).addStringOption(o=>o.setName('footer').setDescription('New footer text').setMaxLength(2048)).addStringOption(o=>o.setName('footer_icon').setDescription('New footer icon URL')).addBooleanOption(o=>o.setName('timestamp').setDescription('Show timestamp')))
    .addSubcommand(s=>s.setName('addfield').setDescription('Add a field').addStringOption(o=>o.setName('name').setDescription('Embed name').setRequired(true).setAutocomplete(true)).addStringOption(o=>o.setName('field_name').setDescription('Field title').setRequired(true).setMaxLength(256)).addStringOption(o=>o.setName('field_value').setDescription('Field value').setRequired(true).setMaxLength(1024)).addBooleanOption(o=>o.setName('inline').setDescription('Inline field')))
    .addSubcommand(s=>s.setName('removefield').setDescription('Remove a field').addStringOption(o=>o.setName('name').setDescription('Embed name').setRequired(true).setAutocomplete(true)).addIntegerOption(o=>o.setName('index').setDescription('1-based field number').setRequired(true).setMinValue(1).setMaxValue(25)))
    .addSubcommand(s=>s.setName('preview').setDescription('Preview a saved embed').addStringOption(o=>o.setName('name').setDescription('Embed name').setRequired(true).setAutocomplete(true)))
    .addSubcommand(s=>s.setName('delete').setDescription('Delete a saved embed').addStringOption(o=>o.setName('name').setDescription('Embed name').setRequired(true).setAutocomplete(true)))
    .addSubcommand(s=>s.setName('list').setDescription('List saved embeds')),
    .addSubcommand(s=>s.setName('editor').setDescription('Open the interactive editor for saved embeds')),
  async execute(interaction){
    if(!interaction.guild)return;await interaction.deferReply({ephemeral:true});const sub=interaction.options.getSubcommand();
    if(sub==='editor'){await interaction.editReply(buildEmbedEditorSelection(interaction.guild.id));return;}
    if(sub==='list'){const data=loadGuild(interaction.guild.id),names=Object.keys(data.savedEmbeds??{});if(!names.length){await interaction.editReply('📭 No saved embeds.');return;}await interaction.editReply({embeds:[new EmbedBuilder().setColor(0x5865F2).setTitle(`🖼️ Saved Embeds (${names.length})`).setDescription(names.map((n,i)=>`**${i+1}.** \`${n}\``).join('\n'))]});return;}
    const name=interaction.options.getString('name',sub==='create'||sub==='edit'||sub==='addfield'||sub==='removefield'||sub==='preview'||sub==='delete')?.toLowerCase().trim();
    if(sub==='create'){if(!name)return;const data=loadGuild(interaction.guild.id);if(data.savedEmbeds?.[name]){await interaction.editReply(`❌ \`${name}\` already exists.`);return;}const rawColor=interaction.options.getString('color'),color=rawColor?parseColor(rawColor):undefined;if(rawColor&&color===undefined){await interaction.editReply('❌ Invalid color.');return;}updateGuild(interaction.guild.id,d=>{if(!d.savedEmbeds)d.savedEmbeds={};d.savedEmbeds[name]={name,title:interaction.options.getString('title')??undefined,description:interaction.options.getString('description')??undefined,color,authorName:interaction.options.getString('author')??undefined,authorIconUrl:interaction.options.getString('author_icon')??undefined,thumbnailUrl:interaction.options.getString('thumbnail')??undefined,imageUrl:interaction.options.getString('image')??undefined,footerText:interaction.options.getString('footer')??undefined,footerIconUrl:interaction.options.getString('footer_icon')??undefined,timestamp:interaction.options.getBoolean('timestamp')??true,fields:[]};});await interaction.editReply({content:`✅ Embed \`${name}\` created.`,embeds:[buildEmbedPreview(loadGuild(interaction.guild.id).savedEmbeds![name])]});return;}
    if(!name){await interaction.editReply('❌ Embed name is required.');return;}const data=loadGuild(interaction.guild.id),saved=data.savedEmbeds?.[name];if(!saved){await interaction.editReply(`❌ No embed named \`${name}\`.`);return;}
    if(sub==='delete'){updateGuild(interaction.guild.id,d=>{delete d.savedEmbeds![name];});await interaction.editReply(`🗑️ Deleted \`${name}\`.`);return;}
    if(sub==='preview'){await interaction.editReply({embeds:[buildEmbedPreview(saved)]});return;}
    if(sub==='addfield'){if((saved.fields?.length??0)>=25){await interaction.editReply('❌ Maximum 25 fields.');return;}updateGuild(interaction.guild.id,d=>{const e=d.savedEmbeds![name];e.fields=e.fields??[];e.fields.push({name:interaction.options.getString('field_name',true),value:interaction.options.getString('field_value',true),inline:interaction.options.getBoolean('inline')??false});});await interaction.editReply({embeds:[buildEmbedPreview(loadGuild(interaction.guild.id).savedEmbeds![name])]});return;}
    if(sub==='removefield'){const index=interaction.options.getInteger('index',true)-1;if(index<0||index>=(saved.fields?.length??0)){await interaction.editReply('❌ That field does not exist.');return;}updateGuild(interaction.guild.id,d=>{d.savedEmbeds![name].fields!.splice(index,1);});await interaction.editReply({embeds:[buildEmbedPreview(loadGuild(interaction.guild.id).savedEmbeds![name])]});return;}
    const rawColor=interaction.options.getString('color'),color=rawColor?parseColor(rawColor):undefined;if(rawColor&&color===undefined){await interaction.editReply('❌ Invalid color.');return;}
    updateGuild(interaction.guild.id,d=>{const e=d.savedEmbeds![name],s=(key:string)=>interaction.options.getString(key);if(s('title')!==null)e.title=s('title')??undefined;if(s('description')!==null)e.description=s('description')??undefined;if(rawColor!==null)e.color=color;if(s('author')!==null)e.authorName=s('author')??undefined;if(s('author_icon')!==null)e.authorIconUrl=s('author_icon')??undefined;if(s('thumbnail')!==null)e.thumbnailUrl=s('thumbnail')??undefined;if(s('image')!==null)e.imageUrl=s('image')??undefined;if(s('footer')!==null)e.footerText=s('footer')??undefined;if(s('footer_icon')!==null)e.footerIconUrl=s('footer_icon')??undefined;const ts=interaction.options.getBoolean('timestamp');if(ts!==null)e.timestamp=ts;});await interaction.editReply({content:`✅ Embed \`${name}\` updated.`,embeds:[buildEmbedPreview(loadGuild(interaction.guild.id).savedEmbeds![name])]});
  },
};
