import { ActionRowBuilder, EmbedBuilder, SlashCommandBuilder, StringSelectMenuBuilder } from 'discord.js';
import type { Command } from '../types.js';
export const HELP_SELECT_CUSTOM_ID='sparxie_help_category';
const EMOJIS:Record<string,string>={Setup:'⚙️',Moderation:'🔨',Security:'🛡️',Channels:'📢',Restrictions:'🚫',Utility:'🛠️',Profiles:'🖼️',Leveling:'📈',Roles:'🎭',Tickets:'🎫',Economy:'⚡',Games:'🎮',Fun:'🎉',Giveaways:'🎁',Music:'🎵',Social:'🌐','Blox Fruits':'🍎',AI:'🤖',Other:'✨'};
const CATEGORY_ORDER=['Setup','Moderation','Security','Channels','Restrictions','Utility','Profiles','Leveling','Roles','Tickets','Economy','Games','Fun','Giveaways','Music','Social','Blox Fruits','AI','Other'];
const PREMIUM=new Set((process.env.SPARXIE_PREMIUM_COMMANDS??'').split(/[\s,]+/i).map(x=>x.trim().toLowerCase()).filter(Boolean));
const CATEGORY_MAP:Record<string,string>={setup:'Setup',autosetup:'Setup',setprefix:'Setup',levelconfig:'Leveling',embed:'Setup',welcome:'Setup',greet:'Setup',ban:'Moderation',kick:'Moderation',mute:'Moderation',unmute:'Moderation',timeout:'Moderation',warn:'Moderation',warnings:'Moderation',clearwarns:'Moderation',warnsleaderboard:'Moderation',nick:'Moderation',temprole:'Moderation',automod:'Security',antinuke:'Security',recovery:'Security',clearchannels:'Security',purge:'Channels',purgebots:'Channels',lock:'Channels',unlock:'Channels',slowmode:'Channels',invitelog:'Channels',chatban:'Restrictions',unchatban:'Restrictions',jail:'Restrictions',unjail:'Restrictions',afk:'Utility',remindme:'Utility',poll:'Utility',snipe:'Utility',editsnipe:'Utility',userinfo:'Utility',serverinfo:'Utility',autoresponder:'Utility',help:'Utility',ping:'Utility',uptime:'Utility',av:'Profiles',banner:'Profiles',rank:'Leveling',leaderboard:'Leveling',createrole:'Roles',roleassign:'Roles',joinrole:'Roles',reactionrole:'Roles',roleconnection:'Roles',inviterole:'Roles',extraowner:'Roles',uploademoji:'Roles',setbloxemojis:'Roles',ticket:'Tickets',closeticket:'Tickets',ticketpanel:'Tickets',coinleaderboard:'Economy',shop:'Economy',removeshop:'Economy',trade:'Economy',game:'Games',games:'Games',gamepolicy:'Games',roast:'Fun',gay:'Fun',pro:'Fun',noob:'Fun',ship:'Fun',giveaway:'Giveaways',giveawaydaily:'Giveaways',music:'Music',socialnotification:'Social',bloxemoji:'Blox Fruits',bloxscanner:'Blox Fruits',bloxvalue:'Blox Fruits',ai:'AI'};
let commandRegistry:Command[]=[];
export function setHelpCommandRegistry(commands:Command[]):void{commandRegistry=commands;}
function categoryFor(name:string):string{return CATEGORY_MAP[name.toLowerCase()]??'Other';}
function emojiFor(category:string):string{return EMOJIS[category]??'✨';}
function resolveCommands(value:any):Command[]{if(Array.isArray(value)&&value.length&&value[0]?.data?.toJSON)return value as Command[];return commandRegistry;}
function optionEntries(data:any,prefix:string){const out:{name:string;description:string}[]=[];for(const option of data.options??[]){if(option.type===1)out.push({name:`${prefix}${data.name} ${option.name}`,description:option.description??'Command option'});else if(option.type===2)for(const sub of option.options??[])if(sub.type===1)out.push({name:`${prefix}${data.name} ${option.name} ${sub.name}`,description:sub.description??'Command option'});}return out;}
export type HelpEntry={name:string;description:string;premium:boolean};export type HelpCategory={name:string;emoji:string;commands:HelpEntry[]};
export function getHelpCategories(commands:any=commandRegistry,prefix='.'):HelpCategory[]{const list=resolveCommands(commands);const buckets=new Map<string,HelpEntry[]>();for(const c of CATEGORY_ORDER)buckets.set(c,[]);for(const command of list){const data:any=command.data.toJSON();const name=String(data.name);const category=categoryFor(name);const premium=PREMIUM.has(name.toLowerCase());buckets.get(category)!.push({name:`${prefix}${name}`,description:String(data.description??'No description available.'),premium});for(const sub of optionEntries(data,prefix))buckets.get(category)!.push({name:sub.name,description:sub.description,premium});}buckets.get('Utility')!.push({name:`${prefix}help <category>`,description:'Open a category directly',premium:false});buckets.get('Games')!.push({name:`${prefix}buy role <name>`,description:'Buy a configured shop role with ⚡ sparks',premium:false},{name:`${prefix}buy colour <name>`,description:'Buy a configured colour with ⚡ sparks',premium:false});return CATEGORY_ORDER.map(name=>({name,emoji:emojiFor(name),commands:buckets.get(name)!.sort((a,b)=>a.name.localeCompare(b.name))})).filter(c=>c.commands.length>0);}
export const HELP_CATEGORIES:HelpCategory[]=[];export const HELP_COMMAND_COUNT=0;
export function findHelpCategory(category?:string|null,commands:any=commandRegistry,prefix='.'):HelpCategory|undefined{if(!category||category.toLowerCase()==='all')return undefined;return getHelpCategories(commands,prefix).find(c=>c.name.toLowerCase()===category.toLowerCase());}
function formatCommand(entry:HelpEntry):string{return`• ${entry.name}${entry.premium?' 🟨':''} — ${entry.description}`;}
export function buildHelpEmbed(category?:string|null,prefix='.',commands:any=commandRegistry):EmbedBuilder{const categories=getHelpCategories(commands,prefix);const selected=category?categories.find(c=>c.name.toLowerCase()===category.toLowerCase()):undefined;const count=categories.reduce((n,c)=>n+c.commands.length,0);const embed=new EmbedBuilder().setColor(0x12d9d3).setAuthor({name:'Sparxie Help Center'}).setFooter({text:'Sparxie • Complete command directory'}).setTimestamp();if(!selected)embed.setTitle('✨ Welcome to Sparxie').setDescription(`Your complete command directory, organized by category.\n\n**Prefix:** \`${prefix}\`\n**Command entries:** \`${count}\`\n**🟨:** Premium feature when premium metadata is configured.\n\n${categories.map(c=>`${c.emoji} **${c.name}** — ${c.commands.length}`).join('\n')}\n\nUse \`${prefix}help <category>\` or the selector below.`);else{embed.setTitle(`${selected.emoji} ${selected.name}`).setDescription(`${selected.commands.length} command entries.\n🟨 = Premium.`);for(let i=0;i<selected.commands.length;i+=10)embed.addFields({name:i?'More commands':'Commands',value:selected.commands.slice(i,i+10).map(formatCommand).join('\n').slice(0,1024)});}return embed;}
export function buildHelpMenu(category?:string|null,commands:any=commandRegistry,prefix='.'):ActionRowBuilder<StringSelectMenuBuilder>{const categories=getHelpCategories(commands,prefix);return new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(HELP_SELECT_CUSTOM_ID).setPlaceholder('Select a category…').addOptions({label:'All commands',description:'Browse the complete command directory',value:'all',default:!category||category==='all',emoji:'📚'},...categories.slice(0,24).map(c=>({label:c.name,description:`${c.commands.length} entries`,value:c.name.toLowerCase(),default:category?.toLowerCase()===c.name.toLowerCase(),emoji:c.emoji}))));}
export const help:Command={data:new SlashCommandBuilder().setName('help').setDescription('Open the complete Sparxie command directory').addStringOption(o=>o.setName('category').setDescription('Show one category').addChoices(...CATEGORY_ORDER.map(c=>({name:`${emojiFor(c)} ${c}`.slice(0,100),value:c.toLowerCase()})))),async execute(interaction){const prefix=(await import('../prefixHandler.js')).getGuildPrefix(interaction.guild?.id??'');const commands=Array.from(interaction.client.commands?.values?.()??commandRegistry);const filter=interaction.options.getString('category');if(filter&&!findHelpCategory(filter,commands,prefix)){await interaction.reply({content:'❌ Unknown help category.',ephemeral:true});return;}await interaction.reply({embeds:[buildHelpEmbed(filter,prefix,commands)],components:[buildHelpMenu(filter,commands,prefix)]});}};
